services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - esnet
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - esnet

  pgsync:
    image: pgsync
    container_name: pgsync
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
      ELASTICSEARCH_URL: http://elasticsearch:9200
      PG_USER: myuser
      PG_PASSWORD: mypassword
    networks:
      - esnet
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - ./pgsync.cnf.json:/app/pgsync.cnf.json
    entrypoint: ["pgsync"]
    command: ["--config", "/app/pgsync.cnf.json"]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch

networks:
  esnet:
    driver: bridge

volumes:
  pg_data:  # Define the named volume for PostgreSQL
